const target = {
  // builder: {
  //   title: "创业者",
  //   img: "/static/img/user_builder.svg",
  //   bg: "#cdc7d3",
  //   text: "Builder",
  // },
  // defi_og: {
  //   title: "DeFi 元老",
  //   img: "/static/img/user_defiog.svg",
  //   bg: "#cdc7d3",
  //   text: "DeFi OG",
  // },
  // meme_og: {
  //   title: "MEME 元老",
  //   img: "/static/img/user_memeog.svg",
  //   bg: "#cdc7d3",
  //   text: "MEME OG",
  // },
  // sandwich_bot: {
  //   title: "机器人",
  //   Icon: {},
  //   img: "/static/img/user_bot.svg",
  //   bg: "#cdc7d3",
  //   text: "Bot",
  // },
  // fresh_wallet: {
  //   title: "新钱包",
  //   img: "/static/img/user_fresh.svg",
  //   Icon: {},
  //   bg: "#e4ffbf",
  //   text: "Fresh",
  // },
  // kol: {
  //   title: "KOL",
  //   img: "/static/img/user_kol.svg",
  //   Icon: {},
  //   bg: "#fecadd",
  //   text: "KOL",
  // },
  smart_degen: {
    title: "聪明钱",
    img: "/static/img/user_smart.svg",
    Icon: {},
    bg: "#fff5da",
    text: "Smart",
  },
  smart_flipper: {
    title: "聪明钱",
    img: "/static/img/user_smart.svg",
    Icon: {},
    bg: "#fff5da",
    text: "Smart",
  },
  vc: {
    title: "VC",
    img: "/static/img/user_vc.svg",
    Icon: {},
    bg: "#b6e9ff",
    text: "VC",
  },
  diamond_hands: {
    title: "钻石手",
    img: "/static/img/user_diamond.svg",
    Icon: {},
    bg: "#b6e9ff",
    text: "Diamond",
  },
  paper_hands: {
    title: "纸手",
    img: "/static/img/user_paper.svg",
    Icon: {},
    defaultColor: "#858E8F",
    bg: "#b6e9ff",
    text: "Paper",
  },
  snipe_bot: {
    title: "狙击手",
    img: "/static/img/user_snpier.svg",
    Icon: {},
    bg: "#fecaca",
    text: "Sniper",
  },
  sniper: {
    title: "狙击手",
    img: "/static/img/user_snpier.svg",
    Icon: {},
    bg: "#fecaca",
    text: "Sniper",
  },
  contract: {
    title: "合约",
    img: "/static/img/user_contract.svg",
    Icon: {},
    bg: "#fecaca",
    text: "Contract",
  },
  scammer: {
    title: "骗子",
    img: "/static/img/user_scam.svg",
    Icon: {},
    bg: "#FF4164",
    text: "Scam",
  },
  top_holder: {
    title: "Top持有者",
    img: "/static/img/user_holder.svg",
    Icon: {},
    defaultColor: "#00AB4A",
    bg: "#FFCF39",
    text: "Top",
  },
  bluechip_owner: {
    title: "蓝筹持有者",
    img: "/static/img/user_holder.svg",
    Icon: {},
    defaultColor: "#93C5FD",
    bg: "#93C5FD",
    text: "BC",
  },
  whale: {
    title: "鲸鱼",
    img: "/static/img/user_holder.svg",
    Icon: {},
    bg: "#FFCF39",
    text: "Whale",
  },
  rat_trader: {
    title: "老鼠仓",
    img: "/static/img/user_holder.svg",
    Icon: {},
    defaultColor: "#DF484C",
    bg: "#FFCF39",
    text: "Insiders",
  },
  pump_smart: {
    title: "Pump聪明钱",
    img: "/static/img/user_holder.svg",
    defaultColor: "#DF484C",
    text: "Pump聪明钱",
  },
  transfer_in: {
    title: "疑似钓鱼钱包，存在代币转入行为",
    defaultColor: "#DF484C",
  },
  dev: {
    title: "代币创建者",
    defaultColor: "#DF484C",
    bg: "#FFCF39",
    text: "代币创建者",
  },
  dev_team: {
    title: "代币创建者小号",
    defaultColor: "#DF484C",
    bg: "#FFCF39",
    text: "代币创建者小号",
  },
};

const downloadList = Object.keys(target).map((key) => {
  return `https://gmgn.ai${target[key as keyof typeof target].img}`;
});

console.log([...new Set(downloadList)]);
